### ISSUE TITLE
Cannot Type

### ISSUE THREAD

**Issue by tchristofferson** [WesJD/AnvilGUI#32]
The GUI pops up but the insert text is blank and you can't type in it because the piece of paper is missing in the left box of the GUI. This was happening before my latest pull request, which is located [here](https://github.com/WesJD/AnvilGUI/pull/31).

**Comment by Speentie8081** [comment]
To be clear your issue is solved by your PR?

**Comment by tchristofferson** [comment]
No, I will make a pull request in about a minute and that will solve this issue.

**Comment by tchristofferson** [comment]
@Speentie8081 I created a pull request that should fix this.

**Comment by tchristofferson** [comment]
Merge request accepted.

**Comment by tchristofferson** [comment]
Still occurs in mc <1.14

**Comment by Trophonix** [comment]
This is still happening for me in earlier versions, at least 1.9 and 1.10. Has the jar been updated since the commit? It seems like it maybe hasn't - navigating to the file in browser shows it was updated 3 days ago.
